### PR TITLE
Descriptions of laws being checked in Haddocks

### PR DESCRIPTION
**Pull request by kozross**
This is meant to (partially) address #8, and define the format for such. I've added natural language descriptions in addition to equations, as I think having both helps aid intuition. I'm not wedded to the chosen format, and am willing to modify these (as well as potentially write the rest).

### CODE REVIEW

**Comment by Lysxia** [comment]
Note: I'm not opposed to adding gitignore, but you can also have global rules that apply to all repositories in your `$HOME/.config/git/ignore` (location configurable by setting `core.excludeFiles` in `.gitconfig`, see also `man gitignore`).

**Comment by Lysxia** [comment]
This looks good to me! Are you planning to add more in this PR?

My main suggestion would be to make it so the constants are hyperlinked:

```
-- @
-- 'callCC' ('const' x) = x
-- @
```

**Comment by kozross** [comment]
@Lysxia I can certainly do that if nobody else is picking this up. I'll make the fix you suggested with the hyperlinks - didn't know Haddocks can do that!

**Comment by solomon-b** [comment]
@kozross I can do this in a few hours if you like.

**Comment by Lysxia** [comment]
@kozross anything you wanted to add before merging this?

**Comment by kozross** [comment]
Nope, I think this covers everything.

**Pull request merged**
